### ISSUE TITLE
w1 - viittauksia vääriin kansioihin

### ISSUE THREAD

**Issue by Creemy** [erja/pilvi#3]
Kohdassa 3 (ESLint Code Checking) sanotaan: 
"ESLint is completely configurable through a configuration file .eslintrc which is located in the 02 Javascript Language directory."
Tiedosto löytyy kuitenkin kansioista 01 Javascript Tools.

Kohdassa 4.1 sanotaan:
"To do this we need to identify these global objects in the .eslintrc file. Locate this in the 06 JavaScript Tools folder and add the following:"
Kansion kuuluisi olla tuo samainen 01 Javascript Tools.

**Comment by erja** [comment]
Corrected.
