### ISSUE TITLE
api.wordnik.com (W2 01AJAX TODO6)

### ISSUE THREAD

**Issue by nnaku** [erja/pilvi#8]
![image](https://user-images.githubusercontent.com/19587635/44858183-1b5f0600-ac7a-11e8-94b5-e5a3df958528.png)

Hidastaa hieman tekemistä kun ko. apin avainta pitää odotella viikonverran.

Voisko tästä olla iloa.
~~https://developer.oxforddictionaries.com/~~ edit: ei salli CORS

**Comment by erja** [comment]
Voisikohan noista jompaa kumpaa käyttää:
https://www.wordsapi.com/docs/
tai
https://dictionaryapi.com/

**Comment by nnaku** [comment]
wordsapi ainakin on vailla luottokorttia.

![image](https://user-images.githubusercontent.com/19587635/44997266-ae1ede00-afb5-11e8-8e8f-1848cc899aa5.png)

**Comment by nnaku** [comment]
https://dictionaryapi.com/
ja tämä palauttaa vain XML muotoisen datan.

Ja chrome seka firefox blockaavat koska Access-Control-Allow-Origin: *
